### ISSUE TITLE
期望能在末尾自动添加各种CRC校验字节

### ISSUE THREAD

**Issue by CatcaptainTeam** [SuperStudio/SuperCom#10]
很多串口通讯需要在数据帧末尾添加CRC校验字节，手工计算很麻烦，希望软件能自动添加。
比如CRC16，CRC32，ADD8，XOR8，ADD16等。

**Comment by SuperStudio** [comment]
> 很多串口通讯需要在数据帧末尾添加CRC校验字节，手工计算很麻烦，希望软件能自动添加。 比如CRC16，CRC32，ADD8，XOR8，ADD16等。

请细说怎么计算

**Comment by CatcaptainTeam** [comment]
具体的算法需要找一些文档来查看。
网上有些在线工具，能够提供一些验证。
比如： http://xnkiot.com/#/crc




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperStudio/SuperCom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月14日(星期五) 晚上10:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperStudio/SuperCom] 期望能在末尾自动添加各种CRC校验字节 (Issue #10)





  
很多串口通讯需要在数据帧末尾添加CRC校验字节，手工计算很麻烦，希望软件能自动添加。 比如CRC16，CRC32，ADD8，XOR8，ADD16等。
  
请细说怎么计算

**Comment by itldg** [comment]
> 

https://github.com/itldg/ITLDG.DataCheck 看看这个符合你的需求不

**Comment by CatcaptainTeam** [comment]
谢谢，这些校验足够了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperStudio/SuperCom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月13日(星期三) 中午11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SuperStudio/SuperCom] 期望能在末尾自动添加各种CRC校验字节 (Issue #10)





   
https://github.com/itldg/ITLDG.DataCheck 看看这个符合你的需求不

**Comment by itldg** [comment]
> 谢谢，这些校验足够了。
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperStudio/SuperCom" ***@***.***&gt;; 发送时间:&nbsp;2023年9月13日(星期三) 中午11:07 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [SuperStudio/SuperCom] 期望能在末尾自动添加各种CRC校验字节 (Issue #10) https://github.com/itldg/ITLDG.DataCheck 看看这个符合你的需求不 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

作者在新的版本中已经加入了此功能,现在已经可以下载预览版体验
