### ISSUE TITLE
日志规则-正则表达式

### ISSUE THREAD

**Issue by ezfantasy** [SuperStudio/SuperCom#12]
感觉日志规则的正则不是标准的，我用java的正则就试别不了，希望能出一个example 贴在github里
然后随便乱写还可能搞崩溃SuperCom，因为写的正则导致崩溃后只能去Highlighting文件夹下去删除自己的规则，否则就一直启动不起来了

**Comment by SuperStudio** [comment]
有弹出什么异常提示吗

**Comment by ezfantasy** [comment]
ICSharpCode.AvalonEdit.Highlighting.HighlightingDefinitionInvalidException: Error at line 24:
正在分析“\CPU\d”－ 无法识别的转义序列 \C。
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XmlHighlightingDefinition.TranslateElementVisitor.CreateRegex(XshdElement position, String regex, XshdRegexType regexType)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XmlHighlightingDefinition.TranslateElementVisitor.VisitRule(XshdRule rule)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XshdRule.AcceptVisitor(IXshdVisitor visitor)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XmlHighlightingDefinition.TranslateElementVisitor.VisitRuleSet(XshdRuleSet ruleSet)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XshdRuleSet.AcceptVisitor(IXshdVisitor visitor)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XshdSyntaxDefinition.AcceptElements(IXshdVisitor visitor)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.XmlHighlightingDefinition..ctor(XshdSyntaxDefinition xshd, IHighlightingDefinitionReferenceResolver resolver)
   在 ICSharpCode.AvalonEdit.Highlighting.Xshd.HighlightingLoader.Load(XshdSyntaxDefinition syntaxDefinition, IHighlightingDefinitionReferenceResolver resolver)
   在 SuperCom.Window_Setting.ApplyRule()

只要已\开头就崩溃了，当然了这个写法也不是正确的

**Comment by SuperStudio** [comment]
正则高亮参考：[HighLight](https://github.com/SuperStudio/SuperCom/wiki/05_HighLight)

不合理的输入将会拦截
