### ISSUE TITLE
串口接收时间戳显示错误

### ISSUE THREAD

**Issue by FatedSpirits** [SuperStudio/SuperCom#15]
收发的时候，时间戳显示蛮奇怪的，收的这一条的时间戳是放在数据末尾，然后新接收一条或者发送一条，就接到上条时间戳后面，可能是逻辑处理方面有问题
![image](https://github.com/SuperStudio/SuperCom/assets/20916788/953ddc5c-3bfc-4df5-b8ff-09b39ad0388b)

**Comment by YM-China** [comment]
重新打开软件，第一条就出现了两个时间戳
![image](https://github.com/SuperStudio/SuperCom/assets/20916788/fe94e354-e169-467f-9801-418100361c9b)

**Comment by SuperStudio** [comment]
这块处理确实有些问题，但是对时间要求精度不大的可忽略

**Comment by itldg** [comment]
这个确实是个问题,在消息收到之前时间戳已经产生了,时间戳与接收消息时间就没有关联了

**Comment by itldg** [comment]
问题已在新版中修复,可以在3.9的正式版中验证
