### ISSUE TITLE
在扩展屏上没法全屏

### ISSUE THREAD

**Issue by Sakur-a** [SuperStudio/SuperCom#17]
笔记本外接拓展事，软件无法在拓展屏上全屏显示，大概是这个样子的。

![image](https://github.com/SuperStudio/SuperCom/assets/62920793/386ffa08-949a-4feb-bc8b-517014ed2615)

**Comment by SuperStudio** [comment]
已修复：[SuperCom-3.8](https://github.com/SuperStudio/SuperCom/releases/tag/3.8)
