### ISSUE TITLE
win10状态栏居左最大化窗口异常

### ISSUE THREAD

**Issue by CQC2016** [SuperStudio/SuperCom#18]
win10 状态栏居左情况下，点击最大化窗口，supercom 似乎仍以状态栏居下的方式铺满窗口。
![image](https://github.com/SuperStudio/SuperCom/assets/23019826/07416b88-7c1a-40c1-a2d1-300157d50d88)

**Comment by SuperStudio** [comment]
已修复：[SuperCom-3.8](https://github.com/SuperStudio/SuperCom/releases/tag/3.8)
