### ISSUE TITLE
日志文件有两列时间戳

### ISSUE THREAD

**Issue by etinovic** [SuperStudio/SuperCom#27]
![image](https://github.com/SuperStudio/SuperCom/assets/42912547/63e2f887-cb26-492f-8ed3-1fb1d145a3d4)

**Comment by itldg** [comment]
后续应该就会修复了 #38

**Comment by SuperStudio** [comment]
改版本已修复：[3.9](https://github.com/SuperStudio/SuperCom/releases/tag/3.9)
