### ISSUE TITLE
是否可以优化一下底部的布局让收码的可视界面更多一些

### ISSUE THREAD

**Issue by canbus** [SuperStudio/SuperCom#32]
底部有3栏的各种按钮及设置按键,是否可以考虑合并成一行,否则太占空间了,特别是在笔记本上使用时.
不用常的(比如波特率设置,语法高亮)是否可以折叠起来

**Comment by SuperStudio** [comment]
可以使用 Ctrl +T 收起来，或者自己手动收起来



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月24日(周四) 中午11:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [SuperStudio/SuperCom] 是否可以优化一下底部的布局让收码的可视界面更多一些 (Issue #32)




 
底部有3栏的各种按钮及设置按键,是否可以考虑合并成一行,否则太占空间了,特别是在笔记本上使用时.
 不用常的(比如波特率设置,语法高亮)是否可以折叠起来
