### ISSUE TITLE
不加回车换行的视觉问题

### ISSUE THREAD

**Issue by steve-joy** [SuperStudio/SuperCom#40]
![issue](https://github.com/SuperStudio/SuperCom/assets/100205322/48fbcd33-0ab0-4425-8cf6-647f6c0fbfe5)

**Comment by itldg** [comment]
测试下新版本是否还有这个问题呢?

**Comment by steve-joy** [comment]
> 测试下新版本是否还有这个问题呢?

没有了，奈斯
