### ISSUE TITLE
时间戳显示不太准确，不精细

### ISSUE THREAD

**Issue by hhxxff** [SuperStudio/SuperCom#52]
我使用两个软件抓取同一个串口log，SuperCom相比SSCOM添加的时间戳不够精细，希望能优化，如下图
![image](https://github.com/SuperStudio/SuperCom/assets/25215552/d5aa94d6-0d10-427a-88fb-18ce6805ac6e)

**Comment by itldg** [comment]
已优化,后续新版本发布时可以再测试下

**Comment by SuperStudio** [comment]
这个问题修复了，可以设置分包时间

[SuperCom-4.0](https://github.com/SuperStudio/SuperCom/releases/tag/4.0)
