### ISSUE TITLE
希望可以添加一个接收hex数据后显示出来，并存储到文件的功能

### ISSUE THREAD

**Issue by chenzhenting2020** [SuperStudio/SuperCom#62]
类似下面图片中的功能：
![f0f26a44b3cee60fab2108d0b05f07b](https://github.com/SuperStudio/SuperCom/assets/55437189/93671c39-9d86-4d56-a15e-a5642b62d0a8)

**Comment by itldg** [comment]
这个功能是有的

![image](https://github.com/SuperStudio/SuperCom/assets/13432299/4230544e-fcaf-40cf-9308-fc2b04e16975)

点击后可以切换为HEX

![image](https://github.com/SuperStudio/SuperCom/assets/13432299/349d195a-0422-4010-b2e7-fae68546a143)
