### ISSUE TITLE
窗口遮挡

### ISSUE THREAD

**Issue by jkcpo** [SuperStudio/SuperCom#7]
你好，我的windows10任务栏放置在左侧，应用窗口全屏时窗口起始点定位错误，被任务栏遮挡了；但应该是反了，因为应用的右侧是空出来的，宽度正好等于左侧任务栏。

**Comment by SuperStudio** [comment]
已修复：[SuperCom-3.8](https://github.com/SuperStudio/SuperCom/releases/tag/3.8)
