### ISSUE TITLE
HEX收发模式

### ISSUE THREAD

**Issue by tiantao433** [SuperStudio/SuperCom#8]
支持HEX收发模式吗？找了半天没找到

**Comment by lingcoln** [comment]
我也没找到，串口协议很多都不是字符，没HEX收发模式的话没法调试

**Comment by Saimean** [comment]
希望增加该功能

**Comment by SuperStudio** [comment]
已实现：[SuperCom-3.6](https://github.com/SuperStudio/SuperCom/releases/tag/3.6)
